#!/usr/bin/perl

use 5.011 ; use strict ; use warnings ; 
use Getopt::Std ; getopts "e:t:v03" , \my%o ; 
use Term::ANSIColor qw/colorstrip color/ ;
use List::MoreUtils qw/any/ ; 

#die "Specify function such -0 " unless $o{0} || $o{3} ; 

$| = 1 if $o{v} ;  
my @exemptLines = split /,/ , ($o{e}//'') ;
while ( <> ) { 
	$_ = &ColorStrip ($_) if $o{0} ; 
 	$_ = &ColorDigits ($_)  if $o{3} ; 
 	$_ = &ColorTabbing ($_,$o{t})  if $o{t} ; 
 	print $_ ;
}
exit(0) ; 
## いろいろな関数

# 色情報の消去
sub ColorStrip ($) { 
	return $_[0] if any { $_ == $. } @exemptLines ;
	return colorstrip($_[0] ) ; 
}

# 指定された数の列のタブごとに、青い背景色をつける。
sub ColorTabbing ($$) { 
	chomp ;
	my @F = split /\t/ , $_[0]  ;
	my @out  ;  
	for ( 0..scalar @F -1){
		 push @out,  ${[color('on_black'),color('on_blue')]} [int($_/$_[1])%2 ]  . $F[$_]  ;
	} 
	return join ("\t",@out).color('reset')."\n" ;
}

## 数字に色をつける。
sub ColorDigits ($) { 
	return $_[0] if any { $_ == $. } @exemptLines ;
	my @accum = &wellSplit ( $_[0] ) ; 
	my $outStr = join '' , map { &wellPrint ($_) } @accum ; 
	return $outStr ; 
}

sub wellPrint ($){
	my $outstr = '' ; 
	sub loc ($) {my $x=$_[0]-1;($x-($x%3))/3 %3 } ; 
	my $str = $_[0] ; 
	if ( $str !~ /^\d/ ) {
		$outstr .=  $_ ; 
		return $outstr ;
	}
	my @wStr = split //, $str  ; 
	for ( -scalar @wStr .. -1 ) { 
		$outstr .= ${[color('cyan'),color('green'),color('yellow')]} [ &loc (-$_) ] . $wStr[$_] ;
	}
	return $outstr.color('white') ;
}

sub wellSplit ($)  { 
	my @wholeStr = split // , $_[0] , -1 ;
	my @accum ;
	my $tmpstr = '' ;  
	my $dflag = 0 ; 
	for ( 0 .. scalar @wholeStr -1 ) { 
		my $c = $wholeStr [ $_ ] ;
		my $dflag0 = $c ge "0" & $c le "9" ; 
		if ( $dflag0 xor $dflag ) { 
		  	push @accum , $tmpstr  if $_ ; 
		  	$tmpstr = $c ;
		  	$dflag = $dflag0 ; 
		} 
		else { 
		  	$tmpstr .= $c ;  
		}
	}
	push @accum, $tmpstr ;
	return @accum ; 
}


__END__ 
=encoding utf8

=head1 color.pl

=head2 色( Term::ANSIColor ) についてのいろいろなユーティリティー

=head3 -0 で入力の色情報を消去する。

=head3 -3 数を3桁ごとに塗り分ける

=head3 -t num タブ区切り num 桁ごとに青の背景色をつける。

=head3 -e linenumbers   コンマ(,)区切りの数を並べると、その行については表示はするが何もしない。

=head3 -v 処理結果をすぐに書き出す。バッファに貯めない。

=cut


