#!/usr/bin/perl
#use 5.014 ; use strict ; use warnings ; # 5.011 5.014 で確認済み
use Getopt::Std ; getopts "e:l:t:v034,:" , \my%o ;
use Term::ANSIColor qw/color colored colorstrip/ ;
$o{','} //= "\t" ;
$| = 1 if $o{v} ;
my %except ; $except {$_} =1 for split /,/ , $o{e}//'' ;
while ( <> ) {
	print $_ if $except{$.} ; # 色情報の消去
	$_ = colorstrip ($_) if $o{0} ;
 	$_ = &ColorDigits ($_)  if $o{3} || $o{4} ;
 	$_ = &ColorTabbing ($_,$o{t})  if $o{t} ;
 	$_ = &ColorLines ($_,$o{t})  if $o{l} ;
 	print $_ ;
}
exit 0 ;

# 指定された数の列のタブごとに、青い背景色をつける。
sub ColorLines ($$) {
    $. % $o{l} == 1 ? colored ( $_ , "on_blue" ) : colored ( $_ , "on_black" ) ;
}

sub ColorTabbing ($$) {
	chomp ;
	my @F = split /$o{','}/ , $_[0]  ;
	my @out  ;
	for ( 0..scalar @F -1){
		 push @out,  color( ['on_black','on_blue']->[int($_/$_[1])%2]  ) . $F[$_]  ;
	}
	return join ($o{','},@out).color('reset')."\n" ;
}

## 数字に色をつける。
sub ColorDigits ($) {
	my @accum = &wellSplit ( $_[0] ) ;
	my $outStr = join '' , map { &wellPrint ($_) } @accum ;
	return $outStr ;
}

sub wellPrint ($){
	my $outstr = '' ;
	sub loc ($) {
        my $x=$_[0]-1;
        my $l = $o{3} ? 3 : $o{4} ? 4 : 5 ; # 5は使わないだろう
        ($x-($x% $l ))/$l %3
        } ;
	my $str = $_[0] ;
	if ( $str !~ /^\d/ ) {
		$outstr .=  $_ ;
		return $outstr ;
	}
	my @wStr = split //, $str ,0  ;
	for ( -scalar @wStr .. -1 ) {
		$outstr .= ${[color('cyan'),color('green'),color('yellow')]} [ &loc (-$_) ] . $wStr[$_] ;
	}
	return $outstr.color('white') ;
}

sub wellSplit ($)  {
	my @wholeStr = split // , $_[0] , -1 ;
	my @accum ;
	my $tmpstr = '' ;
	my $dflag = 0 ;
	for ( 0 .. scalar @wholeStr -1 ) {
		my $c = $wholeStr [ $_ ] ;
		my $dflag0 = $c ge "0" & $c le "9" ;
		if ( $dflag0 xor $dflag ) {
		  	push @accum , $tmpstr  if $_ ;
		  	$tmpstr = $c ;
	  	$dflag = $dflag0 ;
		}
		else {
		  	$tmpstr .= $c ;
		}
	}
	push @accum, $tmpstr ;
	return @accum ;
}


__END__
=encoding utf8

=head1 color.pl

 色( Term::ANSIColor ) についてのいろいろなユーティリティー

 -0 で入力の色情報を消去する。
 -3 数を3桁ごとに塗り分ける
 -4 数を4桁ごとに塗り分ける
 -e linenumbers   コンマ(,)区切りの数を並べると、その行については表示はするが何もしない。
 -l num  :  num行周期で最初の行に背景を青くする。
 -t num タブ区切り num 桁ごとに青の背景色をつける。
 -v 処理結果をすぐに書き出す。バッファに貯めない。

=cut
