#!/usr/bin/perl
use 5.011 ; use strict ; use warnings ;
use Getopt::Std ; getopts "p:d:" , \my %o ; 
use List::MoreUtils qw/any none/ ; 

my @dcols = &procNums ( $o{d} ) if defined $o{d} ; 
my @pcols = &procNums ( $o{p} ) if defined $o{p} ; 
my $nonDefP = ! defined $o{p} ;
&printCols ; 
exit 0 ;

sub printCols { 
	while ( <> ) { 
		chomp ; 
		my @F = split /\t/ , $_ , -1 ;
		@pcols = 0 .. $#F if $nonDefP ; 
		@pcols = &removeNums( \@pcols , \@dcols , scalar @F )  ; #if $nonDefP ;
		print join ( "\t" , @F [ @pcols ] ) , "\n" ; 
	}
}


sub procNums ($) { # まず コンマで分割, # 次に .. を展開する。 # 最後に正の数は 1を引く。
	my @g = split /,/,$_[0]  ; 
	my $l = scalar @g ; 
	for ( 1 .. $l ) { splice @g , $l - $_ , 1 , $1 .. $2 if  $g[ $l - $_ ] =~ m|(.+)\.\.(.+)| }
   for ( 0 .. $#g ) {	$g[$_] -- if $g[$_] > 0 }   ;
	return @g ; 
}

sub removeNums ($$$) { 
	my @res ; 
	@{ $_[0] } = map { $_ >= 0 ? $_ : $_[2] + $_ } @{ $_[0] }  ;
	@{ $_[1] } = map { $_ >= 0 ? $_ : $_[2] + $_ } @{ $_[1] }  ; 
	for my $x ( @{$_[0]} ) { push @res , $x if none { $x == $_ } @{$_[1]} } ;
	return @res ; 
}

sub VERSION_MESSAGE {}
sub HELP_MESSAGE {
	$0 =~ s/.*\/// ; 
	while ( <DATA> ) { 
		s/\$0/$0/g ; 
		print $_ if s/^=head1// .. s/^=cut// ; 
	}
	exit 0 ; 
}

__END__

=encoding utf8

=head1

	$0 -p 5..9,2 -d 6..8 ; # 5列目から9列目の後に2列目を表示するが、ただし6-8列目は省く。 
	$0 -p -1  ; # 最後から1列目のみを表示

=cut


 
